[build-system]
requires = ["setuptools>=41", "setuptools-git-versioning<2"]
build-backend = "setuptools.build_meta"

[project]
name = "cellarium-workflows"
authors = [
    { name = "Cellarium workflows", email = "cas-support@broadinstitute.org" }
]
description = "Cellarium workflows"
requires-python = ">=3.7"
license = { file = "LICENSE" }
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: CPython",
]
dynamic = ["version", "readme"]
dependencies = [
    "google-cloud-aiplatform==1.68.0",
    "google-cloud-pipeline-components==2.17.0",
    "google-cloud-batch==0.17.36",
    "kfp==2.7.0",
    "click==8.1.7",
    "pyjwt==2.9.0",
    "gcsfs",
    "h5py",
    "ruamel.yaml",
]

[project.optional-dependencies]
dev = [
    "tox~=4.6",
    "ruff",
    "pytest~=7.3",
]
train_op = [
    "gcsfs",
    "tensorboard",
    "psutil",
    "ruamel.yaml",
]

[tool.setuptools.packages.find]
include = ["cellarium*"]

[tool.setuptools.package-data]
"cellarium.workflows.scripts" = ["*.sh"]
"cellarium.workflows.example" = ["*.yaml"]

[project.scripts]
cellarium-workflow = "cellarium.workflows.cli:cli"

[tool.setuptools.dynamic]
readme = { file = ["README.md"], content-type = "text/markdown" }

[project.urls]
"Homepage" = "https://cellarium.ai"
"Source Code" = "https://github.com/cellarium-ai/cellarium-workflows"
"Bug Tracker" = "https://github.com/cellarium-ai/cellarium-workflows/issues"
"Discussion Forum" = "https://github.com/cellarium-ai/cellarium-workflows/discussions"

[tool.setuptools-git-versioning]
enabled = true

[tool.black]
line-length = 120
