seed_everything: true
trainer:
  accelerator: cpu
  strategy:
    class_path: lightning.pytorch.strategies.DDPStrategy
    init_args:
      broadcast_buffers: false
  max_epochs: 2
  default_root_dir: ./outputs
model:
  model:
    class_path: cellarium.ml.models.HVGSeuratV3
    init_args:
      n_top_genes: 2000
      use_batch_key: false
      flavor: seurat_v3
      output_path: ./outputs/hvg_genes.csv
data:
  dadc:
    class_path: cellarium.ml.data.DistributedAnnDataCollection
    init_args:
      filenames:
        - data/test_0.h5ad
        - data/test_1.h5ad
        - data/test_2.h5ad
        - data/test_3.h5ad
      limits:
        - 100
        - 200
        - 300
        - 400
      max_cache_size: 2
      indices_strict: true
      obs_columns_to_validate: []
  batch_keys:
    x_ng:
      attr: X
      convert_fn: cellarium.ml.utilities.data.densify
    var_names_g:
      attr: var_names
  batch_size: 5000
  iteration_strategy: cache_efficient
  num_workers: 0
  prefetch_factor: null
  shuffle: true
ckpt_path: null