# lightning.pytorch==2.5.2
seed_everything: true
trainer:
  logger:
  callbacks: 
    - class_path: cellarium.ml.callbacks.PredictionWriter
      init_args:
        output_dir: reconstructions
        prediction_size: null
  max_epochs: 1
  log_every_n_steps: 100
  inference_mode: true
  default_root_dir: 
    gs://cellarium-dev-central/workflows/20260514_human_scvi_glyco_reconstruction
model:
  cpu_transforms:
    - class_path: cellarium.ml.transforms.Filter
      init_args:
        filter_list:
          !FileLoader
          file_path: 
            gs://cellarium-dev-central/workflows/20260514_human_scvi_glyco/20260514_hvg_plus_glyco_genes.csv
          loader_fn: pandas.read_csv
          attr: "feature_id"
          convert_fn: pandas.Series.to_list
  transforms:
    - cellarium.ml.transforms.Densify
  model:
    class_path: cellarium.ml.models.SingleCellVariationalInference
    init_args:

      # reconstruction
      reconstruct_counts_on_predict: true
      reconstruction_transform_batch: 0
      reconstruction_transform_categorical_covariates: null
      reconstruction_var_names_g:
        !FileLoader
          file_path: 
            gs://cellarium-dev-central/workflows/20260514_human_scvi_glyco/20260514_hvg_plus_glyco_genes.csv
          loader_fn: pandas.read_csv
          attr: "feature_id"
          convert_fn: pandas.Series.to_list

      var_names_g: null
      n_batch: null
      n_cats_per_cov: null

      # n_latent_batch: 128
      batch_embedded: false
      batch_representation_sampled: false
      kl_warmup_epochs: 20
      batch_kl_weight_max: 0.0
      use_batch_norm: both
      encoder:
        hidden_layers:
          - class_path: torch.nn.Linear
            init_args:
              out_features: 512
          - class_path: torch.nn.Linear
            init_args:
              out_features: 512
        final_layer:
          class_path: torch.nn.Linear
          init_args: {}
      decoder:
        hidden_layers:
          - class_path: cellarium.ml.models.scvi.LinearWithBatch
            init_args:
              out_features: 512
              label_to_bias_hidden_layers: []
          - class_path: cellarium.ml.models.scvi.LinearWithBatch
            init_args:
              out_features: 512
              label_to_bias_hidden_layers: []
        final_layer:
          class_path: torch.nn.Linear
          init_args: {}
        final_additive_bias: false
      n_latent: 256
  optim_fn: torch.optim.AdamW
  optim_kwargs:
    lr: 1e-4
data:
  dadc:
    class_path: cellarium.ml.data.DistributedAnnDataCollection
    init_args:
      filenames: 
        gs://cellarium-nexus-file-system-3293a8/pipeline/data-extracts/czi_human_primary_gr300genes_fullschema/extract_files/extract_{000000..000100}.h5ad
      shard_size: 10000
      # last_shard_size: 6707
      max_cache_size: 2
  batch_keys:
    x_ng:
      attr: X
      convert_fn: cellarium.ml.utilities.data.keep_sparse
    var_names_g:
      attr: var
      key: feature_id
    batch_index_n:
      attr: obs
      key: assay_dataset_id_donor_id_suspension_type
      convert_fn: cellarium.ml.utilities.data.categories_to_codes
    # categorical_covariate_index_nd:
    #   attr: obs
    #   key:
    #     - suspension_type
    #     - assay
    #   convert_fn: cellarium.ml.utilities.data.categories_to_codes
  batch_size: 1024
  shuffle: true
  num_workers: 8
  prefetch_factor: 4
  persistent_workers: false
ckpt_path: gs://cellarium-dev-central/workflows/20260514_human_scvi_glyco/lightning_logs/version_0/checkpoints/epoch=91-step=8487276.ckpt
